version: "3.9"

services:
  web:
    env_file: .docker-localenv
    build:
      context: ..
      dockerfile: docker/dockerfiles/web
    volumes:
      - ..:/srv/arcademachine/
      - "upload-volume:/srv/arcademachine/media:delegated"  # Might need updating
    container_name: arcademachine-web
    ports:
      - "${DJANGO_PORT:-8000}:8000"
    networks:
      app_net:
        ipv4_address: 172.22.0.2
        aliases:
          - arcademachine-web
    depends_on:
      - db
      - redis
  db:
    container_name: arcademachine-db
    image: postgres:15
    environment:
      POSTGRES_HOST: arcademachine-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: arcademachine
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: arcademachine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - "db-volume:/var/lib/postgresql/data:delegated"
    networks:
      app_net:
        ipv4_address: 172.22.0.3
        aliases:
          - arcademachine-db
  redis:
    container_name: archademachine-redis
    image: redis:7
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - "redis-volume:/var/lib/redis"
    networks:
      app_net:
        ipv4_address: 172.22.0.4
        aliases:
          - arcademachine-redis

volumes:
  db-volume:
    name: arcademachine_db-volume
  redis-volume:
    name: arcademachine_redis-volume
  upload-volume:
    name: arcademachine_upload-volume

networks:
  app_net:
    name: arcademachine-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
