# Generated by Django 3.1 on 2020-08-30 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giantbomb_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(null=True, verbose_name='Year released')),
                ('latitude', models.DecimalField(blank=True, decimal_places=18, default=None, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=18, default=None, max_digits=21, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
            ],
        ),
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
