# Generated by Django 4.2.7 on 2023-12-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='giantbomb_guid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
